title: AI-BASED APPROACHES FOR MARINE OIL SPILL RESPONSE
description: AI-BASED APPROACHES FOR MARINE OIL SPILL RESPONSE
theme: jekyll-theme-cayman
baseurl: "/AI-BASED-APPROACHES-FOR-MARINE-OIL-SPILL-RESPONSE"
plugins:
  - jekyll-seo-tag
